/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApoioRouteImport } from './routes/apoio'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CuidarRouteImport } from './routes/cuidar'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as EscreverRouteImport } from './routes/escrever'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as JardimRouteImport } from './routes/jardim'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MemoriasRouteImport } from './routes/memorias'
import { Route as MuralRouteImport } from './routes/mural'
import { Route as MuralPublicoRouteImport } from './routes/mural-publico'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SelosRouteImport } from './routes/selos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ApiBackupRouteImport } from './routes/api/backup'
import { Route as CartaIdRouteImport } from './routes/carta.$id'
import { Route as ContaRecuperarSenhaRouteImport } from './routes/conta.recuperar-senha'
import { Route as ContaRedefinirSenhaRouteImport } from './routes/conta.redefinir-senha'
import { Route as EscreverConfirmacaoRouteImport } from './routes/escrever.confirmacao'
import { Route as OnboardingPactoRouteImport } from './routes/onboarding.pacto'
import { Route as OnboardingPerfilRouteImport } from './routes/onboarding.perfil'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoioRoute = ApoioRouteImport.update({
  id: '/apoio',
  path: '/apoio',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidarRoute = CuidarRouteImport.update({
  id: '/cuidar',
  path: '/cuidar',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const EscreverRoute = EscreverRouteImport.update({
  id: '/escrever',
  path: '/escrever',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const JardimRoute = JardimRouteImport.update({
  id: '/jardim',
  path: '/jardim',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriasRoute = MemoriasRouteImport.update({
  id: '/memorias',
  path: '/memorias',
  getParentRoute: () => rootRouteImport,
} as any)
const MuralRoute = MuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => rootRouteImport,
} as any)
const MuralPublicoRoute = MuralPublicoRouteImport.update({
  id: '/mural-publico',
  path: '/mural-publico',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SelosRoute = SelosRouteImport.update({
  id: '/selos',
  path: '/selos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackupRoute = ApiBackupRouteImport.update({
  id: '/api/backup',
  path: '/api/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaIdRoute = CartaIdRouteImport.update({
  id: '/carta/$id',
  path: '/carta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRecuperarSenhaRoute = ContaRecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => ContaRoute,
} as any)
const ContaRedefinirSenhaRoute = ContaRedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => ContaRoute,
} as any)
const EscreverConfirmacaoRoute = EscreverConfirmacaoRouteImport.update({
  id: '/confirmacao',
  path: '/confirmacao',
  getParentRoute: () => EscreverRoute,
} as any)
const OnboardingPactoRoute = OnboardingPactoRouteImport.update({
  id: '/onboarding/pacto',
  path: '/onboarding/pacto',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPerfilRoute = OnboardingPerfilRouteImport.update({
  id: '/onboarding/perfil',
  path: '/onboarding/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apoio': typeof ApoioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cuidar': typeof CuidarRoute
  '/diario': typeof DiarioRoute
  '/escrever': typeof EscreverRouteWithChildren
  '/inicio': typeof InicioRoute
  '/instalar': typeof InstalarRoute
  '/jardim': typeof JardimRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/memorias': typeof MemoriasRoute
  '/mural': typeof MuralRoute
  '/mural-publico': typeof MuralPublicoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/selos': typeof SelosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/api/backup': typeof ApiBackupRoute
  '/carta/$id': typeof CartaIdRoute
  '/conta/recuperar-senha': typeof ContaRecuperarSenhaRoute
  '/conta/redefinir-senha': typeof ContaRedefinirSenhaRoute
  '/escrever/confirmacao': typeof EscreverConfirmacaoRoute
  '/onboarding/pacto': typeof OnboardingPactoRoute
  '/onboarding/perfil': typeof OnboardingPerfilRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apoio': typeof ApoioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cuidar': typeof CuidarRoute
  '/diario': typeof DiarioRoute
  '/escrever': typeof EscreverRouteWithChildren
  '/inicio': typeof InicioRoute
  '/instalar': typeof InstalarRoute
  '/jardim': typeof JardimRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/memorias': typeof MemoriasRoute
  '/mural': typeof MuralRoute
  '/mural-publico': typeof MuralPublicoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/selos': typeof SelosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/api/backup': typeof ApiBackupRoute
  '/carta/$id': typeof CartaIdRoute
  '/conta/recuperar-senha': typeof ContaRecuperarSenhaRoute
  '/conta/redefinir-senha': typeof ContaRedefinirSenhaRoute
  '/escrever/confirmacao': typeof EscreverConfirmacaoRoute
  '/onboarding/pacto': typeof OnboardingPactoRoute
  '/onboarding/perfil': typeof OnboardingPerfilRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apoio': typeof ApoioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cuidar': typeof CuidarRoute
  '/diario': typeof DiarioRoute
  '/escrever': typeof EscreverRouteWithChildren
  '/inicio': typeof InicioRoute
  '/instalar': typeof InstalarRoute
  '/jardim': typeof JardimRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/memorias': typeof MemoriasRoute
  '/mural': typeof MuralRoute
  '/mural-publico': typeof MuralPublicoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/selos': typeof SelosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/api/backup': typeof ApiBackupRoute
  '/carta/$id': typeof CartaIdRoute
  '/conta/recuperar-senha': typeof ContaRecuperarSenhaRoute
  '/conta/redefinir-senha': typeof ContaRedefinirSenhaRoute
  '/escrever/confirmacao': typeof EscreverConfirmacaoRoute
  '/onboarding/pacto': typeof OnboardingPactoRoute
  '/onboarding/perfil': typeof OnboardingPerfilRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apoio'
    | '/configuracoes'
    | '/conta'
    | '/contato'
    | '/cuidar'
    | '/diario'
    | '/escrever'
    | '/inicio'
    | '/instalar'
    | '/jardim'
    | '/login'
    | '/mapa'
    | '/memorias'
    | '/mural'
    | '/mural-publico'
    | '/notificacoes'
    | '/perfil'
    | '/planos'
    | '/privacidade'
    | '/selos'
    | '/sobre'
    | '/termos'
    | '/api/backup'
    | '/carta/$id'
    | '/conta/recuperar-senha'
    | '/conta/redefinir-senha'
    | '/escrever/confirmacao'
    | '/onboarding/pacto'
    | '/onboarding/perfil'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apoio'
    | '/configuracoes'
    | '/conta'
    | '/contato'
    | '/cuidar'
    | '/diario'
    | '/escrever'
    | '/inicio'
    | '/instalar'
    | '/jardim'
    | '/login'
    | '/mapa'
    | '/memorias'
    | '/mural'
    | '/mural-publico'
    | '/notificacoes'
    | '/perfil'
    | '/planos'
    | '/privacidade'
    | '/selos'
    | '/sobre'
    | '/termos'
    | '/api/backup'
    | '/carta/$id'
    | '/conta/recuperar-senha'
    | '/conta/redefinir-senha'
    | '/escrever/confirmacao'
    | '/onboarding/pacto'
    | '/onboarding/perfil'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/apoio'
    | '/configuracoes'
    | '/conta'
    | '/contato'
    | '/cuidar'
    | '/diario'
    | '/escrever'
    | '/inicio'
    | '/instalar'
    | '/jardim'
    | '/login'
    | '/mapa'
    | '/memorias'
    | '/mural'
    | '/mural-publico'
    | '/notificacoes'
    | '/perfil'
    | '/planos'
    | '/privacidade'
    | '/selos'
    | '/sobre'
    | '/termos'
    | '/api/backup'
    | '/carta/$id'
    | '/conta/recuperar-senha'
    | '/conta/redefinir-senha'
    | '/escrever/confirmacao'
    | '/onboarding/pacto'
    | '/onboarding/perfil'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApoioRoute: typeof ApoioRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContaRoute: typeof ContaRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CuidarRoute: typeof CuidarRoute
  DiarioRoute: typeof DiarioRoute
  EscreverRoute: typeof EscreverRouteWithChildren
  InicioRoute: typeof InicioRoute
  InstalarRoute: typeof InstalarRoute
  JardimRoute: typeof JardimRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  MemoriasRoute: typeof MemoriasRoute
  MuralRoute: typeof MuralRoute
  MuralPublicoRoute: typeof MuralPublicoRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PerfilRoute: typeof PerfilRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SelosRoute: typeof SelosRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  ApiBackupRoute: typeof ApiBackupRoute
  CartaIdRoute: typeof CartaIdRoute
  OnboardingPactoRoute: typeof OnboardingPactoRoute
  OnboardingPerfilRoute: typeof OnboardingPerfilRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoio': {
      id: '/apoio'
      path: '/apoio'
      fullPath: '/apoio'
      preLoaderRoute: typeof ApoioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidar': {
      id: '/cuidar'
      path: '/cuidar'
      fullPath: '/cuidar'
      preLoaderRoute: typeof CuidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrever': {
      id: '/escrever'
      path: '/escrever'
      fullPath: '/escrever'
      preLoaderRoute: typeof EscreverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jardim': {
      id: '/jardim'
      path: '/jardim'
      fullPath: '/jardim'
      preLoaderRoute: typeof JardimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorias': {
      id: '/memorias'
      path: '/memorias'
      fullPath: '/memorias'
      preLoaderRoute: typeof MemoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mural': {
      id: '/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof MuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mural-publico': {
      id: '/mural-publico'
      path: '/mural-publico'
      fullPath: '/mural-publico'
      preLoaderRoute: typeof MuralPublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selos': {
      id: '/selos'
      path: '/selos'
      fullPath: '/selos'
      preLoaderRoute: typeof SelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backup': {
      id: '/api/backup'
      path: '/api/backup'
      fullPath: '/api/backup'
      preLoaderRoute: typeof ApiBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta/$id': {
      id: '/carta/$id'
      path: '/carta/$id'
      fullPath: '/carta/$id'
      preLoaderRoute: typeof CartaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/recuperar-senha': {
      id: '/conta/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/conta/recuperar-senha'
      preLoaderRoute: typeof ContaRecuperarSenhaRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/redefinir-senha': {
      id: '/conta/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/conta/redefinir-senha'
      preLoaderRoute: typeof ContaRedefinirSenhaRouteImport
      parentRoute: typeof ContaRoute
    }
    '/escrever/confirmacao': {
      id: '/escrever/confirmacao'
      path: '/confirmacao'
      fullPath: '/escrever/confirmacao'
      preLoaderRoute: typeof EscreverConfirmacaoRouteImport
      parentRoute: typeof EscreverRoute
    }
    '/onboarding/pacto': {
      id: '/onboarding/pacto'
      path: '/onboarding/pacto'
      fullPath: '/onboarding/pacto'
      preLoaderRoute: typeof OnboardingPactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/perfil': {
      id: '/onboarding/perfil'
      path: '/onboarding/perfil'
      fullPath: '/onboarding/perfil'
      preLoaderRoute: typeof OnboardingPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContaRouteChildren {
  ContaRecuperarSenhaRoute: typeof ContaRecuperarSenhaRoute
  ContaRedefinirSenhaRoute: typeof ContaRedefinirSenhaRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaRecuperarSenhaRoute: ContaRecuperarSenhaRoute,
  ContaRedefinirSenhaRoute: ContaRedefinirSenhaRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

interface EscreverRouteChildren {
  EscreverConfirmacaoRoute: typeof EscreverConfirmacaoRoute
}

const EscreverRouteChildren: EscreverRouteChildren = {
  EscreverConfirmacaoRoute: EscreverConfirmacaoRoute,
}

const EscreverRouteWithChildren = EscreverRoute._addFileChildren(
  EscreverRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApoioRoute: ApoioRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContaRoute: ContaRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CuidarRoute: CuidarRoute,
  DiarioRoute: DiarioRoute,
  EscreverRoute: EscreverRouteWithChildren,
  InicioRoute: InicioRoute,
  InstalarRoute: InstalarRoute,
  JardimRoute: JardimRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  MemoriasRoute: MemoriasRoute,
  MuralRoute: MuralRoute,
  MuralPublicoRoute: MuralPublicoRoute,
  NotificacoesRoute: NotificacoesRoute,
  PerfilRoute: PerfilRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SelosRoute: SelosRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  ApiBackupRoute: ApiBackupRoute,
  CartaIdRoute: CartaIdRoute,
  OnboardingPactoRoute: OnboardingPactoRoute,
  OnboardingPerfilRoute: OnboardingPerfilRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
